config/routes.rb
FavoriteAthletes::Application.routes.draw do
  resources :athletes

end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  validates_presence_of :name, :sport, :position, :team
  validates_numericality_of :number, :only_integer => true, :greater_than_or_equal_to => 0
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  # GET /athletes
  # GET /athletes.json
  def index
    @athletes = Athlete.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @athletes }
    end
  end

  # GET /athletes/1
  # GET /athletes/1.json
  def show
    @athlete = Athlete.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @athlete }
    end
  end

  # GET /athletes/new
  # GET /athletes/new.json
  def new
    @athlete = Athlete.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @athlete }
    end
  end

  # GET /athletes/1/edit
  def edit
    @athlete = Athlete.find(params[:id])
  end

  # POST /athletes
  # POST /athletes.json
  def create
    @athlete = Athlete.new(params[:athlete])

    respond_to do |format|
      if @athlete.save
        format.html { redirect_to @athlete, notice: 'Athlete was successfully created.' }
        format.json { render json: @athlete, status: :created, location: @athlete }
      else
        format.html { render action: "new" }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /athletes/1
  # PUT /athletes/1.json
  def update
    @athlete = Athlete.find(params[:id])

    respond_to do |format|
      if @athlete.update_attributes(params[:athlete])
        format.html { redirect_to @athlete, notice: 'Athlete was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /athletes/1
  # DELETE /athletes/1.json
  def destroy
    @athlete = Athlete.find(params[:id])
    @athlete.destroy

    respond_to do |format|
      format.html { redirect_to athletes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/_form.html.erb
<%= form_for(@athlete) do |f| %>
  <% if @athlete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@athlete.errors.count, "error") %> prohibited this athlete from being saved:</h2>

      <ul>
      <% @athlete.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sport %><br />
    <%= f.text_field :sport %>
  </div>
  <div class="field">
    <%= f.label :team %><br />
    <%= f.text_field :team %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/athletes/edit.html.erb
<h1>Editing athlete</h1>

<%= render 'form' %>

<%= link_to 'Show', @athlete %> |
<%= link_to 'Back', athletes_path %>

app/views/athletes/index.html.erb
<h1>Listing athletes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Sport</th>
	<th>Team</th>
    <th>Position</th>
    <th>Number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @athletes.each do |athlete| %>
  <tr>
    <td><%= athlete.name %></td>
    <td><%= athlete.sport %></td>
    <td><%= athlete.team %></td>
    <td><%= athlete.position %></td>
    <td><%= athlete.number %></td>
    <td><%= link_to 'Show', athlete %></td>
    <td><%= link_to 'Edit', edit_athlete_path(athlete) %></td>
    <td><%= link_to 'Destroy', athlete, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Athlete', new_athlete_path %>

app/views/athletes/new.html.erb
<h1>New athlete</h1>

<%= render 'form' %>

<%= link_to 'Back', athletes_path %>

app/views/athletes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @athlete.name %>
</p>

<p>
  <b>Sport:</b>
  <%= @athlete.sport %>
</p>

<p>
  <b>Team:</b>
  <%= @athlete.team %>
</p>
<p>
  <b>Position:</b>
  <%= @athlete.position %>
</p>

<p>
  <b>Number:</b>
  <%= @athlete.number %>
</p>


<%= link_to 'Edit', edit_athlete_path(@athlete) %> |
<%= link_to 'Back', athletes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FavoriteAthletes</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>